### ISSUE TITLE
grafana dashboard

### ISSUE THREAD

**Issue by mudaliar** [PureStorage-OpenConnect/pure-fa-openmetrics-exporter#1]
Where can we get grafana dashboard for this exporter? Is there dedicated dashboards for the replication features Active Cluster and ActiveDR etc.. ?

**Comment by sdodsley** [comment]
We are working on example Grafana dashboards for the new v1.0 version of the exporter. 
There is no guarantee that any specific requested dashboard will be created.

**Comment by mudaliar** [comment]
Can we use these https://github.com/PureStorage-OpenConnect/pure-exporter/tree/master/extra/grafana
dashboards if the metrics are same? 
Considering all the issues are closed saying EOF for the old-exporter we have nowhere to go.

**Comment by genegr** [comment]
It might be that some of those dashboards, which by the way are quite outdated, work with minor adjustments, but we cannot actually guarantee that is the case. Those dashboards were designed as examples related to the very first version of the exporters that were deriving the names and labels of the metrics form the Pure REST API 1.x returned attribute, while the new exporter tries to follow as much as possible the names of the objects attributes returned by the 2.x API. A @sdodsley said it is in our plans to provide some example dashboards for the new exporter, more or less designed on the same line of the old example dashboards, but since this is a best effort activity we cannot commit on any release date.

**Comment by mudaliar** [comment]
Thank you @james-laing I will try it out. 
One more question do you also include the load avg for individual FA as well which is only displayed in PURE1?

**Comment by mudaliar** [comment]
@sdodsley I understand that there will be a delay, will I be able to pull it using this new exporter?

**Comment by sdodsley** [comment]
@mudaliar No - the exporter gets telemetry directly from the array. Only Pure1 provides the load number and we can't interface to that in the exporter - different authentication mechanism and also subject to 3rd party firewall rules, or even darksite issues.

**Comment by mudaliar** [comment]
@sdodsley ah! got it. Thanks a lot.
