### ISSUE TITLE
PodReplicaLink is not in seconds

### ISSUE THREAD

**Issue by drhester7** [PureStorage-OpenConnect/pure-fa-openmetrics-exporter#118]
Per Pure's api documentation, PodReplicaLink is returned in milliseconds. Comparing the exporters metric with the data from the pure console, this seems to be true. The console returns data in seconds while the exporter returns data 1000x greater than what is shown in the console.

https://static.pure1.purestorage.com/api-swagger/index.html
![image](https://github.com/PureStorage-OpenConnect/pure-fa-openmetrics-exporter/assets/11220630/e98182ff-9d04-4a8d-ad4d-3d4f613f667b)

**Comment by james-laing** [comment]
@drhester7 thanks for raising this issue.

I've taken a look at the metric `purefa_pod_replica_links_lag_average_sec` and by the name I agree it is describing `_sec` and not `_msec`.

The example you have chosen is the Pure1 REST API swagger, rather than the FlashArray REST API swagger which the OpenMetrics Exporter (OME) uses to scrape metrics.

Having said that, you are still very much correct.  The [FlashArray API swagger](https://support.purestorage.com/FlashArray/PurityFA/Purity_FA_REST_API/FlashArray_REST_API_Reference_Guides) and it is reporting in milliseconds, therefore the OME is reporting in milliseconds.

<img width="1301" alt="Screenshot 2024-03-05 at 22 13 07" src="https://github.com/PureStorage-OpenConnect/pure-fa-openmetrics-exporter/assets/102221031/007c5aab-b5c3-4071-af49-3b1720ab94c5">

Thanks for highlighting this, let us work on how we rectify this issue.

**Comment by drhester7** [comment]
Ah yep. I had seen that there as well and simply didn't know the difference between the APIs. Thanks very much!

**Comment by chrroberts-pure** [comment]
Good find - It's probably a good time to populate [purefa-metrics.md](https://github.com/PureStorage-OpenConnect/pure-fa-openmetrics-exporter/blob/master/specification/metrics/purefa-metrics.md) with the pod metrics too. 

The direction will be to depreciate purefa_pod_replica_links_lag_average_sec in favor of purefa_pod_replica_links_lag_average_msec in the next version, since that matches the Purity API convention.

For now @drhester7 - in your observability platform, you can probably manually select the unit, select msec - and then when you upgrade, the new metric name will populate.
